openapi: 3.0.0
info:
  title: E-Coop API
  version: 1.0.0
  description: API documentation for the E-Coop project
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    /add:
      post:
        summary: Add a new product
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  price:
                    type: number
                  category:
                    type: string
                  image:
                    type: string

        responses:
          "200":
            description: Product added successfully

    /allProducts:
      get:
        summary: Get all products
        responses:
          "200":
            description: A list of all products

  /api/users:
    get:
      summary: Get all users
      responses:
        "200":
          description: A list of users
  /api/cart:
    get:
      summary: Get cart items
      responses:
        "200":
          description: A list of cart items
  /api/orders:
    get:
      summary: Get all orders
      responses:
        "200":
          description: A list of orders
  /api/categories:
    get:
      summary: Get all categories
      responses:
        "200":
          description: A list of categories
