openapi: 3.0.0
info:
  title: E-Coop API
  version: 1.0.0
  description: API documentation for the E-Coop project
servers:
  - url: http://localhost:8080
    description: Development server
paths:
  /api/users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string \
      responses:
        "200":
          description: User registered successfully
        "400":
          description: Bad request - Email already exists
        "500":
          description: Server Error, Unable to Signup

  /api/users/login:
    post:
      summary: Login a users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User logged in successfully
        "401":
          description: Unauthorized - Invalid email or password
        "500":
          description: Server Error, Unable to Login

  /api/users/allUsers:
    get:
      summary: Get all users
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
          description: JWT token for authentication
      responses:
        "200":
          description: A list of all users
        "401":
          description: Unauthorized - Token is missing or invalid
        "500":
          description: Server Error, Unable to get Users

  /api/users/getUser/{id}:
    get:
      summary: Get a user by ID
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
          description: JWT token for authentication
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: User ID
      responses:
        "200":
          description: A user object
        "401":
          description: Unauthorized - Token is missing or invalid
        "500":
          description: Server Error, Unable to get User

  /api/products/add:
    post:
      summary: Add a new product
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
          description: JWT token for authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
                category:
                  type: string
                image:
                  type: string
      responses:
        "200":
          description: Product added successfully
        "401":
          description: Unauthorized - Token is missing or invalid
  /api/products/allProducts:
    get:
      summary: Get all products
      responses:
        "200":
          description: A list of all products
